runtime: nodejs20

env_variables:
  DB_USER: 'cartbutler'
  DB_PASSWORD: 'conestoga8946'
  DB_NAME: 'cartbutler'
  INSTANCE_CONNECTION_NAME: 'cartbutler:us-central1:cartbutler'
  DATABASE_URL: 'mysql://cartbutler_user:%226UiszE%22%5E%230hjk%408@localhost:3306/cartbutler?socket=/cloudsql/cartbutler:us-central1:cartbutler'

beta_settings:
  cloud_sql_instances: 'cartbutler:us-central1:cartbutler'